### ISSUE TITLE
Sprite over light turns light off

### ISSUE THREAD

**Issue by CaiProgramming** [borup3/Lighting-System-2D#6]
So i wasnt sure where to post this but. How do i make it so the point light can't be covered.

**Comment by DavyKoravand** [comment]
I think you can use a separate object for the light, and then make sure the object is drawn over the original sprite. Make the light object follow the original object by syncing their x and y values in the step event.

**Comment by borup3** [comment]
If you put a shadow caster on top of a light source, the light source will cast light inside the shadow caster. You can set a flag on the light to not cast any shadows, or adjust the lighting system to ignore shadow casters when a light source is inside it. This is not part of the system due to it being a heavy performance cost for the general case. You can easily optimize it for your game specifically.
